/**
 * Central icon mapping — semantic name → Lucide component.
 * Use <AppIcon name="..." /> in templates. Never import Lucide icons directly in components.
 *
 * When adding a new icon: pick the semantic name, add it here, done.
 * The whole app updates via this single file.
 */
import {
  // Nav
  Home,
  Dna,
  HeartPulse,
  Milk,
  // Actions
  Plus,
  Pencil,
  Trash2,
  ChevronRight,
  ChevronLeft,
  ChevronDown,
  ChevronUp,
  X,
  Search,
  Filter,
  ArrowRight,
  ArrowLeft,
  // Breeding
  Flame,
  Syringe,
  Baby,
  Leaf,
  CalendarCheck,
  CircleCheck,
  CircleX,
  AlertTriangle,
  // Health
  Stethoscope,
  Pill,
  Activity,
  Thermometer,
  Ban,
  Droplets,
  Utensils,
  // Farm
  Warehouse,
  Settings,
  Users,
  FileText,
  ClipboardList,
  Download,
  Upload,
  Shield,
  Globe,
  // Analytics
  BarChart3,
  TrendingUp,
  PieChart,
  Calculator,
  // Status
  Check,
  Clock,
  CircleDot,
  // Misc
  Bell,
  BookOpen,
  LogOut,
  HelpCircle,
  RefreshCw,
  Eye,
  Lock,
  // Species (Lucide has no cow/sheep — use closest)
  Beef,
  Rabbit,
  // Extra
  Star,
  ExternalLink,
  Info,
  AlertCircle,
  Layers,
  Package,
  Map,
  Zap,
  Send,
  Copy,
  MoreVertical,
  MoreHorizontal,
  ToggleLeft,
  ToggleRight,
  List,
  Grid,
  Calendar,
  User,
  UserPlus,
  UserMinus,
  LogIn,
  Printer,
  Image,
  Maximize,
  Minimize,
  RefreshCcw,
  Database,
  Server,
  Cpu,
  HardDrive,
  Wifi,
  WifiOff,
  CheckCircle,
  XCircle,
  Percent,
  Hash,
  BarChart,
  BarChart2,
  TrendingDown,
  Wrench,
  Signal,
  Tag,
} from 'lucide-vue-next'

/**
 * Map of semantic icon names to Lucide components.
 * Components are raw (not wrapped) — AppIcon handles rendering.
 */
export const iconMap: Record<string, object> = {
  // ── Nav ─────────────────────────────────────────────────────────
  home: Home,
  dna: Dna,
  'heart-pulse': HeartPulse,
  milk: Milk,
  'milk-bucket': Milk,

  // ── Actions ─────────────────────────────────────────────────────
  plus: Plus,
  add: Plus,
  edit: Pencil,
  pencil: Pencil,
  'trash-2': Trash2,
  trash: Trash2,
  delete: Trash2,
  'chevron-right': ChevronRight,
  'chevron-left': ChevronLeft,
  'chevron-down': ChevronDown,
  'chevron-up': ChevronUp,
  x: X,
  close: X,
  search: Search,
  filter: Filter,
  'arrow-right': ArrowRight,
  'arrow-left': ArrowLeft,

  // ── Breeding ─────────────────────────────────────────────────────
  flame: Flame,
  heat: Flame,
  syringe: Syringe,
  'ai-insemination': Syringe,
  baby: Baby,
  calving: Baby,
  lambing: Baby,
  leaf: Leaf,
  'dry-off': Leaf,
  'calendar-check': CalendarCheck,
  'preg-check': CalendarCheck,
  'circle-check': CircleCheck,
  'circle-x': CircleX,
  'alert-triangle': AlertTriangle,
  warning: AlertTriangle,
  abortion: AlertTriangle,

  // ── Health ───────────────────────────────────────────────────────
  stethoscope: Stethoscope,
  pill: Pill,
  medication: Pill,
  activity: Activity,
  thermometer: Thermometer,
  ban: Ban,
  blocked: Ban,
  droplets: Droplets,
  'milk-drop': Droplets,
  utensils: Utensils,
  meat: Utensils,

  // ── Farm ─────────────────────────────────────────────────────────
  warehouse: Warehouse,
  farm: Warehouse,
  settings: Settings,
  users: Users,
  'file-text': FileText,
  'clipboard-list': ClipboardList,
  download: Download,
  upload: Upload,
  export: Download,
  import: Upload,
  shield: Shield,
  globe: Globe,

  // ── Animals (species-specific) ───────────────────────────────────
  // Lucide has no cow/sheep. Use Beef as cattle placeholder, Rabbit for generic.
  cow: Beef,
  bull: Beef,
  cattle: Beef,
  sheep: Rabbit,
  ram: Rabbit,
  animal: Beef,

  // ── Analytics ────────────────────────────────────────────────────
  'bar-chart-3': BarChart3,
  'bar-chart': BarChart,
  'bar-chart-2': BarChart2,
  'trending-up': TrendingUp,
  'trending-down': TrendingDown,
  'pie-chart': PieChart,
  calculator: Calculator,
  analytics: BarChart3,
  percent: Percent,
  hash: Hash,

  // ── Status ───────────────────────────────────────────────────────
  check: Check,
  clock: Clock,
  'circle-dot': CircleDot,
  'check-circle': CheckCircle,
  'x-circle': XCircle,
  'alert-circle': AlertCircle,
  info: Info,

  // ── Misc ─────────────────────────────────────────────────────────
  bell: Bell,
  notification: Bell,
  'book-open': BookOpen,
  'log-out': LogOut,
  logout: LogOut,
  'log-in': LogIn,
  login: LogIn,
  'help-circle': HelpCircle,
  help: HelpCircle,
  sync: RefreshCw,
  'refresh-cw': RefreshCw,
  'refresh-ccw': RefreshCcw,
  refresh: RefreshCw,
  eye: Eye,
  view: Eye,
  lock: Lock,
  star: Star,
  'external-link': ExternalLink,
  layers: Layers,
  package: Package,
  map: Map,
  zap: Zap,
  send: Send,
  copy: Copy,
  'more-vertical': MoreVertical,
  'more-horizontal': MoreHorizontal,
  'toggle-left': ToggleLeft,
  'toggle-right': ToggleRight,
  list: List,
  grid: Grid,
  calendar: Calendar,
  user: User,
  'user-plus': UserPlus,
  'user-minus': UserMinus,
  printer: Printer,
  image: Image,
  maximize: Maximize,
  minimize: Minimize,
  database: Database,
  server: Server,
  cpu: Cpu,
  'hard-drive': HardDrive,
  wifi: Wifi,
  'wifi-off': WifiOff,
  wrench: Wrench,
  maintenance: Wrench,
  signal: Signal,
  tag: Tag,
  label: Tag,
}
