const PDFDocument = require('pdfkit')
const ExcelJS = require('exceljs')
const db = require('../config/database')

// ── Helpers ──────────────────────────────────────────────────

async function getFarmName(farmId) {
  if (!farmId) return 'MyHerder Farm'
  const row = await db('app_settings').where({ key: 'farm_name' }).where('farm_id', farmId).first()
  return row?.value || 'MyHerder Farm'
}

function formatDate(dateStr) {
  if (!dateStr) return ''
  const d = new Date(dateStr)
  return d.toISOString().slice(0, 10)
}

function formatDateTime(dateStr) {
  if (!dateStr) return ''
  const d = new Date(dateStr)
  return `${d.toISOString().slice(0, 10)} ${d.toISOString().slice(11, 16)}`
}

// ── PDF Generation ───────────────────────────────────────────

const BRAND_GREEN = '#2D6A4F'
const PAGE_MARGIN = 40
const FONT_REGULAR = 'Helvetica'
const FONT_BOLD = 'Helvetica-Bold'

function createPdfDocument({ title, farmName, dateRange, generatedBy }) {
  const doc = new PDFDocument({
    size: 'A4',
    layout: 'landscape',
    margins: { top: PAGE_MARGIN, bottom: PAGE_MARGIN, left: PAGE_MARGIN, right: PAGE_MARGIN },
    bufferPages: true,
  })

  const chunks = []
  doc.on('data', (chunk) => chunks.push(chunk))

  // Header
  doc.fontSize(18).fillColor(BRAND_GREEN).font(FONT_BOLD).text(farmName, { align: 'center' })
  doc.moveDown(0.3)
  doc.fontSize(14).fillColor('#333').text(title, { align: 'center' })
  doc.moveDown(0.3)
  doc.fontSize(9).fillColor('#666').font(FONT_REGULAR)
    .text(`${dateRange.from} — ${dateRange.to}`, { align: 'center' })
  doc.moveDown(0.2)
  doc.text(`Generated by ${generatedBy} on ${formatDateTime(new Date().toISOString())}`, { align: 'center' })
  doc.moveDown(1)

  function finalize() {
    const pageCount = doc.bufferedPageRange().count

    // Suppress auto-pagination while adding page numbers — PDFKit's text()
    // near the page bottom triggers addPage(), creating phantom blank pages
    const _addPage = doc.addPage.bind(doc)
    doc.addPage = () => doc

    for (let i = 0; i < pageCount; i++) {
      doc.switchToPage(i)
      doc.fontSize(8).fillColor('#999').font(FONT_REGULAR)
        .text(`Page ${i + 1} of ${pageCount}`, PAGE_MARGIN, doc.page.height - 30, {
          width: doc.page.width - PAGE_MARGIN * 2,
          align: 'center',
          lineBreak: false,
        })
    }

    doc.addPage = _addPage
    doc.end()
    return new Promise((resolve) => {
      doc.on('end', () => resolve(Buffer.concat(chunks)))
    })
  }

  return { doc, finalize }
}

function drawPdfTable(doc, { columns, rows, summaryRow }) {
  const pageWidth = doc.page.width - PAGE_MARGIN * 2
  const totalWeight = columns.reduce((sum, c) => sum + (c.width || 1), 0)
  const colWidths = columns.map((c) => ((c.width || 1) / totalWeight) * pageWidth)
  const rowHeight = 18
  const headerHeight = 22
  const fontSize = 7.5
  const headerFontSize = 8

  function drawRow(y, cells, isHeader, isSummary) {
    const height = isHeader ? headerHeight : rowHeight
    let x = PAGE_MARGIN

    if (isHeader) {
      doc.rect(x, y, pageWidth, height).fill(BRAND_GREEN)
    } else if (isSummary) {
      doc.moveTo(x, y).lineTo(x + pageWidth, y).strokeColor('#333').lineWidth(1).stroke()
    }

    for (let i = 0; i < columns.length; i++) {
      const text = String(cells[i] ?? '')
      const font = isHeader || isSummary ? FONT_BOLD : FONT_REGULAR
      const color = isHeader ? '#FFFFFF' : '#333'
      const fSize = isHeader ? headerFontSize : fontSize

      doc.font(font).fontSize(fSize).fillColor(color)
      doc.text(text, x + 3, y + (height - fSize) / 2, {
        width: colWidths[i] - 6,
        height,
        ellipsis: true,
        lineBreak: false,
      })
      x += colWidths[i]
    }
    return height
  }

  function checkPageBreak(y, needed) {
    if (y + needed > doc.page.height - PAGE_MARGIN - 30) {
      doc.addPage()
      return PAGE_MARGIN
    }
    return y
  }

  // Header row
  let y = doc.y
  y = checkPageBreak(y, headerHeight)
  drawRow(y, columns.map((c) => c.header), true, false)
  y += headerHeight

  // Data rows
  for (const row of rows) {
    y = checkPageBreak(y, rowHeight)
    const cells = columns.map((c) => row[c.key])
    drawRow(y, cells, false, false)
    y += rowHeight
  }

  // Summary row
  if (summaryRow) {
    y = checkPageBreak(y, rowHeight + 4)
    y += 4
    const cells = columns.map((c) => summaryRow[c.key] ?? '')
    drawRow(y, cells, false, true)
    y += rowHeight
  }

  doc.y = y + 10
}

// ── Excel Generation ─────────────────────────────────────────

async function createExcelReport({ title, sheetName, farmName, dateRange, generatedBy, columns, rows, summaryRow }) {
  const wb = new ExcelJS.Workbook()
  wb.creator = 'MyHerder'
  wb.created = new Date()

  const ws = wb.addWorksheet(sheetName || 'Report')

  // Title rows
  const titleRow = ws.addRow([farmName])
  titleRow.font = { size: 16, bold: true, color: { argb: 'FF2D6A4F' } }
  ws.mergeCells(1, 1, 1, columns.length)

  const subtitleRow = ws.addRow([title])
  subtitleRow.font = { size: 12, bold: true }
  ws.mergeCells(2, 1, 2, columns.length)

  const rangeRow = ws.addRow([`${dateRange.from} — ${dateRange.to}`])
  rangeRow.font = { size: 9, color: { argb: 'FF666666' } }
  ws.mergeCells(3, 1, 3, columns.length)

  const genRow = ws.addRow([`Generated by ${generatedBy} on ${formatDateTime(new Date().toISOString())}`])
  genRow.font = { size: 9, color: { argb: 'FF666666' } }
  ws.mergeCells(4, 1, 4, columns.length)

  ws.addRow([]) // blank row

  // Header row
  const headerRow = ws.addRow(columns.map((c) => c.header))
  headerRow.eachCell((cell) => {
    cell.font = { bold: true, color: { argb: 'FFFFFFFF' } }
    cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF2D6A4F' } }
    cell.alignment = { vertical: 'middle', horizontal: 'center' }
    cell.border = {
      bottom: { style: 'thin', color: { argb: 'FF1B4332' } },
    }
  })

  // Freeze header
  ws.views = [{ state: 'frozen', ySplit: 6 }]

  // Data rows
  for (const row of rows) {
    ws.addRow(columns.map((c) => row[c.key] ?? ''))
  }

  // Summary row
  if (summaryRow) {
    const sRow = ws.addRow(columns.map((c) => summaryRow[c.key] ?? ''))
    sRow.eachCell((cell) => {
      cell.font = { bold: true }
      cell.border = { top: { style: 'medium', color: { argb: 'FF333333' } } }
    })
  }

  // Auto column widths
  for (let i = 0; i < columns.length; i++) {
    const colIdx = i + 1
    const headerLen = String(columns[i].header).length
    let maxLen = headerLen
    for (const row of rows) {
      const val = String(row[columns[i].key] ?? '')
      if (val.length > maxLen) maxLen = val.length
    }
    ws.getColumn(colIdx).width = Math.min(Math.max(maxLen + 2, 10), 40)
  }

  return wb.xlsx.writeBuffer()
}

// ── Response Helper ──────────────────────────────────────────

function sendFile(res, buffer, filename, format) {
  if (format === 'xlsx') {
    res.set('Content-Type', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet')
    res.set('Content-Disposition', `attachment; filename="${filename}.xlsx"`)
  } else {
    res.set('Content-Type', 'application/pdf')
    res.set('Content-Disposition', `attachment; filename="${filename}.pdf"`)
  }
  res.send(buffer)
}

module.exports = {
  getFarmName,
  formatDate,
  createPdfDocument,
  drawPdfTable,
  createExcelReport,
  sendFile,
}
